networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  woodpecker:
    image: woodpeckerci/woodpecker-server:${COMPOSE_SERVER_TAG}
    networks:
      - app
      - frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8000
    volumes:
      - .docker/data/server:/var/lib/woodpecker/
    environment:
      - WOODPECKER_HOST=${WOODPECKER_HOST}
      - WOODPECKER_OPEN=true
      - WOODPECKER_ORGS=${WOODPECKER_ORGS}
      - WOODPECKER_ADMIN=${WOODPECKER_ADMIN}
      - WOODPECKER_GITHUB=true
      - WOODPECKER_GITHUB_CLIENT=${WOODPECKER_GITHUB_CLIENT}
      - WOODPECKER_GITHUB_SECRET=${WOODPECKER_GITHUB_SECRET}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_DATABASE_DRIVER=mysql
      - WOODPECKER_DATABASE_DATASOURCE=${WOODPECKER_DATABASE_DATASOURCE}
      - WOODPECKER_CONFIG_SERVICE_ENDPOINT=${WOODPECKER_CONFIG_SERVICE_ENDPOINT}
      - WOODPECKER_DEFAULT_CANCEL_PREVIOUS_PIPELINE_EVENTS=${WOODPECKER_DEFAULT_CANCEL_PREVIOUS_PIPELINE_EVENTS}
      - WOODPECKER_PROMETHEUS_AUTH_TOKEN=${WOODPECKER_PROMETHEUS_AUTH_TOKEN}
      - WOODPECKER_METRICS_SERVER_ADDR=${WOODPECKER_METRICS_SERVER_ADDR}
      - WOODPECKER_GRPC_SECURE=true
      - WOODPECKER_GRPC_VERIFY=true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # web server
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8000"

      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.middlewares=redirect-to-https"

      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.rule=Host(`${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.service=${COMPOSE_PROJECT_NAME}"

      # gRPC service
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-grpc.loadbalancer.server.port=9000"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-grpc.loadbalancer.server.scheme=h2c"

      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-grpc.rule=Host(`grpc-${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-grpc.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-grpc.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-grpc.middlewares=redirect-to-https"

      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-grpcs.rule=Host(`grpc-${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-grpcs.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-grpcs.service=${COMPOSE_PROJECT_NAME}-grpc"
