{
 "title": "Woodpecker",
 "description": "This is a dashboard for the Woodpecker prometehus endpoint ",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pending steps",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "woodpecker_pending_steps{job=\"woodpecker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "woodpecker_worker_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Repo count",
   "type": "stat",
   "description": "The amount of woodpecker repos",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "woodpecker_repo_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "woodpecker_user_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current running steps",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "woodpecker_running_steps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total pipeline runs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "woodpecker_pipeline_total_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}