---
- name: Call Github REST API
  become: false
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Call GitHub API
      uri:
        url: https://api.github.com/repos/itk-devops/itkdev-deploy-test/releases/tags/0.0.2
        method: GET
        headers: {
          "Accept": "application/vnd.github+json",
          #"Authorization": "Bearer YOUR_JWT"
        }

      register: results

    - debug:
        var: results