---
- name: ITK Dev Deploy Playbook
  hosts: localhost
  remote_user: test
  vars:
    REMOTE_BASE_PATH: "../../data/www"

  # Expected environment
  # - CI_REPO_OWNER : GitHub org
  # - CI_REPO_NAME : Repository
  # - CI_COMMIT_TAG: Git tag
  # - COMPOSE_SERVER_DOMAIN: Domain for the application

  tasks:
    - name: Set Install Path
      ansible.builtin.set_fact:
        server_install_path: "{{ REMOTE_BASE_PATH }}/{{ COMPOSE_SERVER_DOMAIN | replace('.', '_') }}"
        github_tar_url: "https://github.com/{{ CI_REPO_OWNER }}/{{ CI_REPO_NAME }}/releases/download/{{ CI_COMMIT_TAG}}/{{ CI_REPO_NAME }}-{{ CI_COMMIT_TAG }}.tar.gz"
        github_checksum_url: "https://github.com/{{ CI_REPO_OWNER }}/{{ CI_REPO_NAME }}/releases/download/{{ CI_COMMIT_TAG}}/checksum.txt"

    - debug:
        msg:
          - "server_install_path: {{ server_install_path }}"
          - "github_tar_url: {{ github_tar_url }}"
          - "github_checksum_url: {{ github_checksum_url }}"
            
    # @TODO: Lock file
    # @TODO: Backup options

    - name: Create temp directory
      ansible.builtin.file:
        path: "{{ server_install_path }}/temp"
        state: directory
        mode: '0755'

    - name: Download build tar
      ansible.builtin.get_url:
        url: "{{ github_tar_url }}"
        # checksum cannot have path it seems
        #checksum: sha256:{{ github_checksum_url }}
        dest: "{{ server_install_path }}/temp/"

    - name: Create release directory
      ansible.builtin.file:
        path: "{{ server_install_path }}/releases/{{ CI_COMMIT_TAG }}/"
        state: directory
        mode: '0755'

#    - name: Expand build tar
#      ansible.builtin.unarchive:
#        src: "{{ server_install_path }}/temp/{{ CI_REPO_NAME }}-{{ CI_COMMIT_TAG }}.tar.gz"
#        dest: "{{ server_install_path }}/releases/{{ CI_COMMIT_TAG }}/"

    - name: Stop Docker containers
      ansible.builtin.command: /usr/local/bin/itkdev-docker-compose-server stop
      args:
        chdir: "{{ server_install_path }}/htdocs/"

    # @TODO: Fix shared dirs/files

    - name: Symlink htdocs to latest release
      ansible.builtin.file:
        src: "{{ server_install_path }}/releases/{{ CI_COMMIT_TAG }}/"
        dest: "{{ server_install_path }}/htdocs"
        state: link
        force: yes

    - name: Pull Docker containers
      ansible.builtin.command: /usr/local/bin/itkdev-docker-compose-server pull
      args:
        chdir: "{{ server_install_path }}/htdocs/"

    - name: Start Docker containers
      ansible.builtin.command: /usr/local/bin/itkdev-docker-compose-server up --detach --force-recreate --remove-orphans
      args:
        chdir: "{{ server_install_path }}/htdocs/"

    - name: Cleanup temp directory
      ansible.builtin.file:
        path: "{{ server_install_path }}/temp"
        state: absent

    # @TODO: Run commands
    # @TODO: Crontab?
